### ISSUE TITLE
Documentation on deployment to Openshift

### ISSUE THREAD

**Issue by juaneschutte** [cryptonomicon314/flog#1]
Hi cryptonomicon314,

Im trying to get a simple Flask-AppBuilder app setup on Openshift as per the issue here ...
https://github.com/dpgaspar/Flask-AppBuilder/issues/170

Would like to here your advice on how to get the scripts right in .openshift/action_hooks/ to initialise the db, create admin and run the testdata.py 

Any help is appreciated.
Juane

**Comment by cryptonomicon314** [comment]
Actually, I just initialize the DB manually over SSH.
I still haven't updated flog to run with the latest version of AppBuilder, so I have never created an admin user with the new script. I'll look into it when I have the time, but I'm afraid I can't hep you right now...

**Comment by juaneschutte** [comment]
That worked!  Thank you!  Will eventually put it into a script to automate but the manual work is good for now.
